
name: unittest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: UnitTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run mvn
        run: mvn -B clean verify
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

    linter:
      name: Linter
      runs-on: ubuntu-latest

      steps:
        - name: Linter Style
          run: mvn checkstyle:check

        - name: Linter 2
          run: mvn checkstyle:checkstyle
      
