
name: unittest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: UnitTest
    runs-on: ubuntu-latest
    needs: console
    strategy:
          matrix:
            version: [11,17,21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Up JDK21
        uses: actions/setup-java@v4
        
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run mvn
        run: mvn -B clean verify
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: console

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
  console:
    name: Konsolenjobs
    runs-on: ubuntu-latest

    env:
      name: test
    steps:
      - name: Dialog
        run: echo $Greeting $name, Passwort = $Password_Use ${{ secrets.LECTURE_PASSWORD }}!
        env:
          Password_use: 'passwort123'
      
      
